# The URL the site will be built for
base_url = "https://lyudmilivanov.com"
title = "Lyudmil Ivanov"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Taxonomies
taxonomies = [{ name = "tags", feed = true}]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

links = [
     { title = "Home", href = "/" },
     { title = "Posts", href = "/blog" },
     { title = "Tags", href = "/tags" },
     { title = "About", href = "/about" },
]